CREATE TABLE [dbo].[Music_Genre]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY,
	[Music_Id] INT NOT NULL,
	[Genre_Id] INT NOT NULL,


	CONSTRAINT FK_MUSIC_GENRE_MUSIC_ID FOREIGN KEY (Music_Id) REFERENCES dbo.[Music](Id),
	CONSTRAINT FK_MUSIC_GENRE_GENRE_ID FOREIGN KEY (Genre_Id) REFERENCES dbo.[Genre](Id)
)
